name = "seafoodexpress"
type = "javascript"
compatibility_date = "2025-07-01"

[assets]
directory = "./"

exclude = [
  ".git", ".git/**",
  "node_modules", "node_modules/**",
  ".github", ".github/**",
  ".vscode",
  "*.log",
  "README.md"
]